export const FETCH_WEATHER_LIST_START = 'FETCH_WEATHER_LIST_START';
export const FETCH_WEATHER_LIST_SUCCESS = 'FETCH_WEATHER_LIST_SUCCESS';
export const FETCH_WEATHER_LIST_ERROR = 'FETCH_WEATHER_LIST_ERROR';

export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';

export const DAY_SELECTED = 'DAY_SELECTED';

